// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/kraken/tracker/peerstore (interfaces: Store)

package mockpeerstore

import (
	gomock "github.com/golang/mock/gomock"
	core "github.com/uber/kraken/core"
	reflect "reflect"
)

// MockStore is a mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockStore) EXPECT() *MockStoreMockRecorder {
	return _m.recorder
}

// GetPeers mocks base method
func (_m *MockStore) GetPeers(_param0 core.InfoHash, _param1 int) ([]*core.PeerInfo, error) {
	ret := _m.ctrl.Call(_m, "GetPeers", _param0, _param1)
	ret0, _ := ret[0].([]*core.PeerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeers indicates an expected call of GetPeers
func (_mr *MockStoreMockRecorder) GetPeers(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetPeers", reflect.TypeOf((*MockStore)(nil).GetPeers), arg0, arg1)
}

// UpdatePeer mocks base method
func (_m *MockStore) UpdatePeer(_param0 core.InfoHash, _param1 *core.PeerInfo) error {
	ret := _m.ctrl.Call(_m, "UpdatePeer", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePeer indicates an expected call of UpdatePeer
func (_mr *MockStoreMockRecorder) UpdatePeer(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UpdatePeer", reflect.TypeOf((*MockStore)(nil).UpdatePeer), arg0, arg1)
}
