// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/kraken/lib/hostlist (interfaces: List)

package mockhostlist

import (
	gomock "github.com/golang/mock/gomock"
	stringset "github.com/uber/kraken/utils/stringset"
	reflect "reflect"
)

// MockList is a mock of List interface
type MockList struct {
	ctrl     *gomock.Controller
	recorder *MockListMockRecorder
}

// MockListMockRecorder is the mock recorder for MockList
type MockListMockRecorder struct {
	mock *MockList
}

// NewMockList creates a new mock instance
func NewMockList(ctrl *gomock.Controller) *MockList {
	mock := &MockList{ctrl: ctrl}
	mock.recorder = &MockListMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockList) EXPECT() *MockListMockRecorder {
	return _m.recorder
}

// Resolve mocks base method
func (_m *MockList) Resolve() stringset.Set {
	ret := _m.ctrl.Call(_m, "Resolve")
	ret0, _ := ret[0].(stringset.Set)
	return ret0
}

// Resolve indicates an expected call of Resolve
func (_mr *MockListMockRecorder) Resolve() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Resolve", reflect.TypeOf((*MockList)(nil).Resolve))
}
