// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/kraken/lib/backend/hdfsbackend/webhdfs (interfaces: Client)

package mockwebhdfs

import (
	gomock "github.com/golang/mock/gomock"
	webhdfs "github.com/uber/kraken/lib/backend/hdfsbackend/webhdfs"
	io "io"
	reflect "reflect"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockClient) EXPECT() *MockClientMockRecorder {
	return _m.recorder
}

// Create mocks base method
func (_m *MockClient) Create(_param0 string, _param1 io.Reader) error {
	ret := _m.ctrl.Call(_m, "Create", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (_mr *MockClientMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Create", reflect.TypeOf((*MockClient)(nil).Create), arg0, arg1)
}

// GetFileStatus mocks base method
func (_m *MockClient) GetFileStatus(_param0 string) (webhdfs.FileStatus, error) {
	ret := _m.ctrl.Call(_m, "GetFileStatus", _param0)
	ret0, _ := ret[0].(webhdfs.FileStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileStatus indicates an expected call of GetFileStatus
func (_mr *MockClientMockRecorder) GetFileStatus(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetFileStatus", reflect.TypeOf((*MockClient)(nil).GetFileStatus), arg0)
}

// ListFileStatus mocks base method
func (_m *MockClient) ListFileStatus(_param0 string) ([]webhdfs.FileStatus, error) {
	ret := _m.ctrl.Call(_m, "ListFileStatus", _param0)
	ret0, _ := ret[0].([]webhdfs.FileStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFileStatus indicates an expected call of ListFileStatus
func (_mr *MockClientMockRecorder) ListFileStatus(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ListFileStatus", reflect.TypeOf((*MockClient)(nil).ListFileStatus), arg0)
}

// Mkdirs mocks base method
func (_m *MockClient) Mkdirs(_param0 string) error {
	ret := _m.ctrl.Call(_m, "Mkdirs", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mkdirs indicates an expected call of Mkdirs
func (_mr *MockClientMockRecorder) Mkdirs(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Mkdirs", reflect.TypeOf((*MockClient)(nil).Mkdirs), arg0)
}

// Open mocks base method
func (_m *MockClient) Open(_param0 string, _param1 io.Writer) error {
	ret := _m.ctrl.Call(_m, "Open", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Open indicates an expected call of Open
func (_mr *MockClientMockRecorder) Open(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Open", reflect.TypeOf((*MockClient)(nil).Open), arg0, arg1)
}

// Rename mocks base method
func (_m *MockClient) Rename(_param0 string, _param1 string) error {
	ret := _m.ctrl.Call(_m, "Rename", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rename indicates an expected call of Rename
func (_mr *MockClientMockRecorder) Rename(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Rename", reflect.TypeOf((*MockClient)(nil).Rename), arg0, arg1)
}
