// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/kraken/lib/healthcheck (interfaces: PassiveFilter)

package mockhealthcheck

import (
	gomock "github.com/golang/mock/gomock"
	stringset "github.com/uber/kraken/utils/stringset"
	reflect "reflect"
)

// MockPassiveFilter is a mock of PassiveFilter interface
type MockPassiveFilter struct {
	ctrl     *gomock.Controller
	recorder *MockPassiveFilterMockRecorder
}

// MockPassiveFilterMockRecorder is the mock recorder for MockPassiveFilter
type MockPassiveFilterMockRecorder struct {
	mock *MockPassiveFilter
}

// NewMockPassiveFilter creates a new mock instance
func NewMockPassiveFilter(ctrl *gomock.Controller) *MockPassiveFilter {
	mock := &MockPassiveFilter{ctrl: ctrl}
	mock.recorder = &MockPassiveFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockPassiveFilter) EXPECT() *MockPassiveFilterMockRecorder {
	return _m.recorder
}

// Failed mocks base method
func (_m *MockPassiveFilter) Failed(_param0 string) {
	_m.ctrl.Call(_m, "Failed", _param0)
}

// Failed indicates an expected call of Failed
func (_mr *MockPassiveFilterMockRecorder) Failed(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Failed", reflect.TypeOf((*MockPassiveFilter)(nil).Failed), arg0)
}

// Run mocks base method
func (_m *MockPassiveFilter) Run(_param0 stringset.Set) stringset.Set {
	ret := _m.ctrl.Call(_m, "Run", _param0)
	ret0, _ := ret[0].(stringset.Set)
	return ret0
}

// Run indicates an expected call of Run
func (_mr *MockPassiveFilterMockRecorder) Run(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Run", reflect.TypeOf((*MockPassiveFilter)(nil).Run), arg0)
}
