// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/kraken/lib/persistedretry (interfaces: Store)

package mockpersistedretry

import (
	gomock "github.com/golang/mock/gomock"
	persistedretry "github.com/uber/kraken/lib/persistedretry"
	reflect "reflect"
)

// MockStore is a mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockStore) EXPECT() *MockStoreMockRecorder {
	return _m.recorder
}

// AddFailed mocks base method
func (_m *MockStore) AddFailed(_param0 persistedretry.Task) error {
	ret := _m.ctrl.Call(_m, "AddFailed", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFailed indicates an expected call of AddFailed
func (_mr *MockStoreMockRecorder) AddFailed(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AddFailed", reflect.TypeOf((*MockStore)(nil).AddFailed), arg0)
}

// AddPending mocks base method
func (_m *MockStore) AddPending(_param0 persistedretry.Task) error {
	ret := _m.ctrl.Call(_m, "AddPending", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPending indicates an expected call of AddPending
func (_mr *MockStoreMockRecorder) AddPending(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "AddPending", reflect.TypeOf((*MockStore)(nil).AddPending), arg0)
}

// Find mocks base method
func (_m *MockStore) Find(_param0 interface{}) ([]persistedretry.Task, error) {
	ret := _m.ctrl.Call(_m, "Find", _param0)
	ret0, _ := ret[0].([]persistedretry.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (_mr *MockStoreMockRecorder) Find(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Find", reflect.TypeOf((*MockStore)(nil).Find), arg0)
}

// GetFailed mocks base method
func (_m *MockStore) GetFailed() ([]persistedretry.Task, error) {
	ret := _m.ctrl.Call(_m, "GetFailed")
	ret0, _ := ret[0].([]persistedretry.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFailed indicates an expected call of GetFailed
func (_mr *MockStoreMockRecorder) GetFailed() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetFailed", reflect.TypeOf((*MockStore)(nil).GetFailed))
}

// GetPending mocks base method
func (_m *MockStore) GetPending() ([]persistedretry.Task, error) {
	ret := _m.ctrl.Call(_m, "GetPending")
	ret0, _ := ret[0].([]persistedretry.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPending indicates an expected call of GetPending
func (_mr *MockStoreMockRecorder) GetPending() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetPending", reflect.TypeOf((*MockStore)(nil).GetPending))
}

// MarkFailed mocks base method
func (_m *MockStore) MarkFailed(_param0 persistedretry.Task) error {
	ret := _m.ctrl.Call(_m, "MarkFailed", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkFailed indicates an expected call of MarkFailed
func (_mr *MockStoreMockRecorder) MarkFailed(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "MarkFailed", reflect.TypeOf((*MockStore)(nil).MarkFailed), arg0)
}

// MarkPending mocks base method
func (_m *MockStore) MarkPending(_param0 persistedretry.Task) error {
	ret := _m.ctrl.Call(_m, "MarkPending", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPending indicates an expected call of MarkPending
func (_mr *MockStoreMockRecorder) MarkPending(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "MarkPending", reflect.TypeOf((*MockStore)(nil).MarkPending), arg0)
}

// Remove mocks base method
func (_m *MockStore) Remove(_param0 persistedretry.Task) error {
	ret := _m.ctrl.Call(_m, "Remove", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove
func (_mr *MockStoreMockRecorder) Remove(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Remove", reflect.TypeOf((*MockStore)(nil).Remove), arg0)
}
