// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/kraken/origin/blobclient (interfaces: Client)

package mockblobclient

import (
	gomock "github.com/golang/mock/gomock"
	core "github.com/uber/kraken/core"
	io "io"
	reflect "reflect"
	time "time"
)

// MockClient is a mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockClient) EXPECT() *MockClientMockRecorder {
	return _m.recorder
}

// Addr mocks base method
func (_m *MockClient) Addr() string {
	ret := _m.ctrl.Call(_m, "Addr")
	ret0, _ := ret[0].(string)
	return ret0
}

// Addr indicates an expected call of Addr
func (_mr *MockClientMockRecorder) Addr() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Addr", reflect.TypeOf((*MockClient)(nil).Addr))
}

// DeleteBlob mocks base method
func (_m *MockClient) DeleteBlob(_param0 core.Digest) error {
	ret := _m.ctrl.Call(_m, "DeleteBlob", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlob indicates an expected call of DeleteBlob
func (_mr *MockClientMockRecorder) DeleteBlob(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DeleteBlob", reflect.TypeOf((*MockClient)(nil).DeleteBlob), arg0)
}

// DownloadBlob mocks base method
func (_m *MockClient) DownloadBlob(_param0 string, _param1 core.Digest, _param2 io.Writer) error {
	ret := _m.ctrl.Call(_m, "DownloadBlob", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadBlob indicates an expected call of DownloadBlob
func (_mr *MockClientMockRecorder) DownloadBlob(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DownloadBlob", reflect.TypeOf((*MockClient)(nil).DownloadBlob), arg0, arg1, arg2)
}

// DuplicateUploadBlob mocks base method
func (_m *MockClient) DuplicateUploadBlob(_param0 string, _param1 core.Digest, _param2 io.Reader, _param3 time.Duration) error {
	ret := _m.ctrl.Call(_m, "DuplicateUploadBlob", _param0, _param1, _param2, _param3)
	ret0, _ := ret[0].(error)
	return ret0
}

// DuplicateUploadBlob indicates an expected call of DuplicateUploadBlob
func (_mr *MockClientMockRecorder) DuplicateUploadBlob(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DuplicateUploadBlob", reflect.TypeOf((*MockClient)(nil).DuplicateUploadBlob), arg0, arg1, arg2, arg3)
}

// ForceCleanup mocks base method
func (_m *MockClient) ForceCleanup(_param0 time.Duration) error {
	ret := _m.ctrl.Call(_m, "ForceCleanup", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForceCleanup indicates an expected call of ForceCleanup
func (_mr *MockClientMockRecorder) ForceCleanup(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ForceCleanup", reflect.TypeOf((*MockClient)(nil).ForceCleanup), arg0)
}

// GetMetaInfo mocks base method
func (_m *MockClient) GetMetaInfo(_param0 string, _param1 core.Digest) (*core.MetaInfo, error) {
	ret := _m.ctrl.Call(_m, "GetMetaInfo", _param0, _param1)
	ret0, _ := ret[0].(*core.MetaInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetaInfo indicates an expected call of GetMetaInfo
func (_mr *MockClientMockRecorder) GetMetaInfo(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetMetaInfo", reflect.TypeOf((*MockClient)(nil).GetMetaInfo), arg0, arg1)
}

// GetPeerContext mocks base method
func (_m *MockClient) GetPeerContext() (core.PeerContext, error) {
	ret := _m.ctrl.Call(_m, "GetPeerContext")
	ret0, _ := ret[0].(core.PeerContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeerContext indicates an expected call of GetPeerContext
func (_mr *MockClientMockRecorder) GetPeerContext() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetPeerContext", reflect.TypeOf((*MockClient)(nil).GetPeerContext))
}

// Locations mocks base method
func (_m *MockClient) Locations(_param0 core.Digest) ([]string, error) {
	ret := _m.ctrl.Call(_m, "Locations", _param0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Locations indicates an expected call of Locations
func (_mr *MockClientMockRecorder) Locations(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Locations", reflect.TypeOf((*MockClient)(nil).Locations), arg0)
}

// OverwriteMetaInfo mocks base method
func (_m *MockClient) OverwriteMetaInfo(_param0 core.Digest, _param1 int64) error {
	ret := _m.ctrl.Call(_m, "OverwriteMetaInfo", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// OverwriteMetaInfo indicates an expected call of OverwriteMetaInfo
func (_mr *MockClientMockRecorder) OverwriteMetaInfo(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "OverwriteMetaInfo", reflect.TypeOf((*MockClient)(nil).OverwriteMetaInfo), arg0, arg1)
}

// ReplicateToRemote mocks base method
func (_m *MockClient) ReplicateToRemote(_param0 string, _param1 core.Digest, _param2 string) error {
	ret := _m.ctrl.Call(_m, "ReplicateToRemote", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplicateToRemote indicates an expected call of ReplicateToRemote
func (_mr *MockClientMockRecorder) ReplicateToRemote(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ReplicateToRemote", reflect.TypeOf((*MockClient)(nil).ReplicateToRemote), arg0, arg1, arg2)
}

// Stat mocks base method
func (_m *MockClient) Stat(_param0 string, _param1 core.Digest) (*core.BlobInfo, error) {
	ret := _m.ctrl.Call(_m, "Stat", _param0, _param1)
	ret0, _ := ret[0].(*core.BlobInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat
func (_mr *MockClientMockRecorder) Stat(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Stat", reflect.TypeOf((*MockClient)(nil).Stat), arg0, arg1)
}

// StatLocal mocks base method
func (_m *MockClient) StatLocal(_param0 string, _param1 core.Digest) (*core.BlobInfo, error) {
	ret := _m.ctrl.Call(_m, "StatLocal", _param0, _param1)
	ret0, _ := ret[0].(*core.BlobInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatLocal indicates an expected call of StatLocal
func (_mr *MockClientMockRecorder) StatLocal(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "StatLocal", reflect.TypeOf((*MockClient)(nil).StatLocal), arg0, arg1)
}

// TransferBlob mocks base method
func (_m *MockClient) TransferBlob(_param0 core.Digest, _param1 io.Reader) error {
	ret := _m.ctrl.Call(_m, "TransferBlob", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransferBlob indicates an expected call of TransferBlob
func (_mr *MockClientMockRecorder) TransferBlob(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "TransferBlob", reflect.TypeOf((*MockClient)(nil).TransferBlob), arg0, arg1)
}

// UploadBlob mocks base method
func (_m *MockClient) UploadBlob(_param0 string, _param1 core.Digest, _param2 io.Reader) error {
	ret := _m.ctrl.Call(_m, "UploadBlob", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadBlob indicates an expected call of UploadBlob
func (_mr *MockClientMockRecorder) UploadBlob(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UploadBlob", reflect.TypeOf((*MockClient)(nil).UploadBlob), arg0, arg1, arg2)
}
