// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/kraken/origin/blobclient (interfaces: ClusterClient)

package mockblobclient

import (
	gomock "github.com/golang/mock/gomock"
	core "github.com/uber/kraken/core"
	io "io"
	reflect "reflect"
)

// MockClusterClient is a mock of ClusterClient interface
type MockClusterClient struct {
	ctrl     *gomock.Controller
	recorder *MockClusterClientMockRecorder
}

// MockClusterClientMockRecorder is the mock recorder for MockClusterClient
type MockClusterClientMockRecorder struct {
	mock *MockClusterClient
}

// NewMockClusterClient creates a new mock instance
func NewMockClusterClient(ctrl *gomock.Controller) *MockClusterClient {
	mock := &MockClusterClient{ctrl: ctrl}
	mock.recorder = &MockClusterClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockClusterClient) EXPECT() *MockClusterClientMockRecorder {
	return _m.recorder
}

// DownloadBlob mocks base method
func (_m *MockClusterClient) DownloadBlob(_param0 string, _param1 core.Digest, _param2 io.Writer) error {
	ret := _m.ctrl.Call(_m, "DownloadBlob", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadBlob indicates an expected call of DownloadBlob
func (_mr *MockClusterClientMockRecorder) DownloadBlob(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "DownloadBlob", reflect.TypeOf((*MockClusterClient)(nil).DownloadBlob), arg0, arg1, arg2)
}

// GetMetaInfo mocks base method
func (_m *MockClusterClient) GetMetaInfo(_param0 string, _param1 core.Digest) (*core.MetaInfo, error) {
	ret := _m.ctrl.Call(_m, "GetMetaInfo", _param0, _param1)
	ret0, _ := ret[0].(*core.MetaInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetaInfo indicates an expected call of GetMetaInfo
func (_mr *MockClusterClientMockRecorder) GetMetaInfo(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetMetaInfo", reflect.TypeOf((*MockClusterClient)(nil).GetMetaInfo), arg0, arg1)
}

// OverwriteMetaInfo mocks base method
func (_m *MockClusterClient) OverwriteMetaInfo(_param0 core.Digest, _param1 int64) error {
	ret := _m.ctrl.Call(_m, "OverwriteMetaInfo", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

// OverwriteMetaInfo indicates an expected call of OverwriteMetaInfo
func (_mr *MockClusterClientMockRecorder) OverwriteMetaInfo(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "OverwriteMetaInfo", reflect.TypeOf((*MockClusterClient)(nil).OverwriteMetaInfo), arg0, arg1)
}

// Owners mocks base method
func (_m *MockClusterClient) Owners(_param0 core.Digest) ([]core.PeerContext, error) {
	ret := _m.ctrl.Call(_m, "Owners", _param0)
	ret0, _ := ret[0].([]core.PeerContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Owners indicates an expected call of Owners
func (_mr *MockClusterClientMockRecorder) Owners(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Owners", reflect.TypeOf((*MockClusterClient)(nil).Owners), arg0)
}

// ReplicateToRemote mocks base method
func (_m *MockClusterClient) ReplicateToRemote(_param0 string, _param1 core.Digest, _param2 string) error {
	ret := _m.ctrl.Call(_m, "ReplicateToRemote", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplicateToRemote indicates an expected call of ReplicateToRemote
func (_mr *MockClusterClientMockRecorder) ReplicateToRemote(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "ReplicateToRemote", reflect.TypeOf((*MockClusterClient)(nil).ReplicateToRemote), arg0, arg1, arg2)
}

// Stat mocks base method
func (_m *MockClusterClient) Stat(_param0 string, _param1 core.Digest) (*core.BlobInfo, error) {
	ret := _m.ctrl.Call(_m, "Stat", _param0, _param1)
	ret0, _ := ret[0].(*core.BlobInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat
func (_mr *MockClusterClientMockRecorder) Stat(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Stat", reflect.TypeOf((*MockClusterClient)(nil).Stat), arg0, arg1)
}

// UploadBlob mocks base method
func (_m *MockClusterClient) UploadBlob(_param0 string, _param1 core.Digest, _param2 io.Reader) error {
	ret := _m.ctrl.Call(_m, "UploadBlob", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadBlob indicates an expected call of UploadBlob
func (_mr *MockClusterClientMockRecorder) UploadBlob(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "UploadBlob", reflect.TypeOf((*MockClusterClient)(nil).UploadBlob), arg0, arg1, arg2)
}
